ResourceCenter.WebUI/Areas/Admin/Controllers/FormController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using ResourceCenter.WebCore.Modules.Forms.Models;
using ResourceCenter.WebCore.Modules.Forms.Services;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Areas.Admin.Controllers
{
    public class FormController : DistributorAuthorizedController
    {
        private readonly IFormService _service;

        public FormController(IFormService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Grid_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_service.GetList().ToDataSourceResult(request));
        }

        [HttpPost]
        public Task<ActionResult> Grid_Create([DataSourceRequest] DataSourceRequest request, FormModel model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Create(model));

        }

        [HttpPost]
        public Task<ActionResult> Grid_Update([DataSourceRequest] DataSourceRequest request, FormModel model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Update(model));
        }

        [HttpPost]
        public Task<ActionResult> Grid_Destroy([DataSourceRequest] DataSourceRequest request, FormModel model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Delete(model));
        }

        public ViewResult Preview(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Preview(int id, PreviewFormModel model)
        {
            model.PreviewForm = await _service.GetLeadForm(id, model.Language);
            return View(model);
        }
     
    }
}

ResourceCenter.WebUI/Areas/Reseller/Controllers/AttributeValueController.cs
using System.Web.Mvc;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Areas.Reseller.Controllers
{
    public class AttributeValueController : ResellerAuthorizedController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

ResourceCenter.WebUI/Areas/Reseller/Views/AttributeValue/Index.cshtml
@using Core.Localization
@using Core.Web.Extensions
<h2>Lead Form Preview</h2>

@using (Html.FormPost())
{
    <span>Language: </span>
    @(Html.Kendo().DropDownList()
        .Name("LanguageCode")
        .DataValueField("Name")
        .DataTextField("DisplayName")
        .HtmlAttributes(new { style = "width: 300px" })
        .BindTo(ViewBag.Languages as IList<LanguageInfo>)
        .Deferred()
    )

    <button class="btn btn-primary">
        <i class="fa fa-search"></i> Preview
    </button>
    <button type="button" class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Form")'">
        <i class="fa fa-undo"></i> Back
    </button>
}