ResourceCenter.WebUI/Areas/Resources/Controllers/DefaultController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using ResourceCenter.WebCore.Filters;
using ResourceCenter.WebCore.Modules.Resellers.Query;
using ResourceCenter.WebCore.Modules.Resellers.Services;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Areas.Resources.Controllers
{
    [ResourceAuthorize]
    public class DefaultController : BaseController
    {
        private readonly IContentService _contentService;

        public DefaultController(IContentService contentService)
        {
            _contentService = contentService;
        }

        public ActionResult Index(PagedAssetsQuery query)
        {
            return View(_contentService.GetAssets(query));
        }

        public async Task<ActionResult> Detail(AssetDetailQuery query)
        {
            var result = await _contentService.GetAssetDetail(query);
            if (result == null)
            {
                return RedirectToAction("Index");
            }
            return View(result);
        }

        public async Task<PartialViewResult> AssetLeadForm(AssetDetailQuery query)
        {
            ViewBag.ResellerId = query.ResellerId;
            var model = await _contentService.GetAssetLeadForm(query.AssetId, query.Lang);
            return PartialView(model);
        }
    }
}

ResourceCenter.WebUI/Controllers/DownloadController.cs
using System;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Extensions;
using ResourceCenter.WebCore.Models;
using ResourceCenter.WebCore.Services;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Controllers
{
    public class DownloadController : BaseController
    {
        private readonly IDownloadService _downloadService;

        public DownloadController(IDownloadService downloadService)
        {
            _downloadService = downloadService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Asset(DownloadModel model)
        {
            if (!ModelState.IsValid)
            {
               throw BadRequestException();
            }

            try
            {
                var result = await _downloadService.DownloadAsset(model, Request);
                if (result.HasFile)
                {
                    AddContentHeader(result.FileName);
                    return File(result.Data, result.ContentType);
                }
            }
            catch (Exception ex)
            {
                throw BadRequestException(ex.GetBaseErrorMessage());
            }

            throw NotFoundException();
        }

        private void AddContentHeader(string fileName)
        {
            var cd = new ContentDisposition
            {
                FileName = fileName,
                Inline = false
            };

            Response.Headers.Add("Content-Disposition", cd.ToString());
        }
    }
}

ResourceCenter.WebUI/Areas/Resources/Views/Default/AssetLeadForm.cshtml
@using ResourceCenter.WebUI.Infrastructure.Extensions
@model ResourceCenter.WebCore.Modules.Forms.Models.LeadFormModel

<h4>@Model.Name</h4>
<p>@Model.Description</p>

@using (Html.BeginForm("Asset", "Download", new { area = "" }, FormMethod.Post, new { novalidate = "" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("AssetId", Model.AssetId)
    @Html.Hidden("FormId", Model.Id)
    @Html.Hidden("ResellerId", (int)ViewBag.ResellerId)

    foreach (var item in Model.Fields)
    {
        @Html.LeadFieldEditor(item)
    }
    <div class="text-right">
        <button class="btn btn-primary ladda-button">
            <i class="fa fa-cloud-download"></i> Download
        </button>
    </div>
}

ResourceCenter.WebUI/Areas/Resources/Views/Default/Detail.cshtml
@using Core.Extensions
@using Core.Web.Extensions
@using Core.Web.UI.PagedList
@using ResourceCenter.WebCore.Extensions
@using ResourceCenter.WebUI.Infrastructure.Extensions
@model ResourceCenter.WebCore.Modules.Resellers.Models.TranslatedAssetModel

<div class="col-lg-12">
    <div class="ibox product-detail">
        <div class="ibox-content product-box custom">
            <div class="row">
                <div class="col-md-5">
                    <div class="product-imitation detailItem">
                        @if (string.IsNullOrEmpty(Model.Thumbnail))
                        {
                            <div class="icon">
                                <span></span>@Html.IconFileType(Model.FileName.FileExtension())
                            </div>
                        }
                        else
                        {
                            <span></span><img alt="image" class="img-responsive" src="@Model.Thumbnail">
                        }
                    </div>
                </div>
                <div class="col-md-7">
                    <h2 class="font-bold m-b-xs">
                        @Model.AssetTitle
                    </h2>
                    <small>@Model.ShortDescription</small>
                    <div class="m-t-md">
                        <h2 class="product-main-price">@Model.FileName</h2>
                    </div>
                    <hr>

                    <h4>Product description</h4>

                    <div class="small text-muted">
                        @Model.LongDescription
                    </div>
                    <dl class="small m-t-md">
                        <dt>File name</dt>
                        <dd>@Model.FileName</dd>
                        <dt>File type</dt>
                        <dd>@Model.FileName.FileExtension()</dd>
                        <dt>Uploaded date</dt>
                        <dd>@Model.CreatedDate</dd>
                    </dl>
                    <hr>

                    <div>
                        @if (!Model.IsGated)
                        {
                            <form id="form" method="post" action="@Url.Action("Asset", "Download", new {area = ""})">
                                @Html.AntiForgeryToken()
                                @Html.Hidden("AssetId", Model.Id)
                                @Html.Hidden("ResellerId", ViewContext.RequestContext.ResellerId())

                                <button class="btn btn-default">
                                    <i class="fa fa-cloud-download"></i> Download
                                </button>
                            </form>
                        }
                        else
                        {
                            <button id="btDownload" class="btn btn-primary" data-toggle="modal" data-target="#modal">
                                <i class="fa fa-cloud-download"></i> Download
                            </button>

                            @Html.ModalPartial()

                            @section scripts{
                                @ViewHelper.RenderPageScript("resources/default-detail");
                                <script>
                                    $(function () {
                                        var baseUrl = '@Url.Action("AssetLeadForm")',
                                            formData = {
                                                assetId: '@ViewContext.RequestContext.AssetId()',
                                                resellerId: '@ViewContext.RequestContext.ResellerId()',
                                                tenantId: '@ViewContext.RequestContext.TenantId()',
                                                lang: '@ViewContext.RequestContext.LanguageCode()'
                                            };
                                        detailCtrl.init(baseUrl, formData);
                                    });
                                </script>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ResourceCenter.WebUI/Areas/Resources/Views/Default/Index.cshtml
@using Core.Extensions
@using Core.Web.UI.PagedList
@using ResourceCenter.WebCore.Extensions
@using ResourceCenter.WebUI.Infrastructure.Extensions

@model Core.Infrastructure.Paging.IPagedList<ResourceCenter.WebCore.Modules.Resellers.Models.TranslatedAssetModel>

<div>
    <div class="ibox-content m-b-sm border-bottom">
        <div class="ibox-tools">
            <div class="btn-group">
                <a id="btGrid" href="#" class="btn btn-white btn-sm"><i class="fa fa-th"></i> Grid </a>
                <a id="btList" href="#" class="btn btn-white btn-sm"><i class="fa fa-th-list"></i> List </a>
            </div>
        </div>
    </div>

    <div class="row" id="productView">
        @foreach (var item in Model)
        {
            <div class="listDiv">
                @Html.Partial("_ListItem", item)
            </div>

            <div class="gridDiv">
                @Html.Partial("_GridItem", item)
            </div>
        }
    </div>

    <div class="text-center">
        @Html.PagedListPager(Model,
            page => Url.Action("Index", "Default", ViewContext.RequestContext.ToPagedAssetsRouteValues(page)))
    </div>
</div>

@section scripts{
    @ViewHelper.RenderPageScript("resources/resource-list")
}

ResourceCenter.WebUI/Areas/Resources/Views/Default/_GridItem.cshtml
@using Core.Extensions
@using Core.Web.UI.PagedList
@model ResourceCenter.WebCore.Modules.Resellers.Models.TranslatedAssetModel

@using ResourceCenter.WebCore.Extensions
<div class="col-md-3 col-sm-4 col-xs-6">
    <div class="ibox">
        <div class="ibox-content product-box custom">
            <div class="product-imitation gridItem">
                @if (string.IsNullOrEmpty(Model.Thumbnail))
                {
                    <div class="icon">
                        <span></span>@Html.IconFileType(Model.FileName.FileExtension())
                    </div>
                }
                else
                {
                    <span></span><img alt="image" class="img-responsive" src="@Model.Thumbnail">
                }
            </div>
            <div class="product-desc">
                <h4 class="text-center">
                    @Model.AssetTitle
                </h4>

                <div class="m-t text-center">
                    <a class="btn btn-xs btn-outline btn-primary" href="@Url.Action("Detail", "Default", ViewContext.RequestContext.ToAssetDetailsRouteValues(Model.Id))">
                        View Details
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

ResourceCenter.WebUI/Areas/Resources/Views/Default/_ListItem.cshtml
@using Core.Extensions
@using Core.Web.UI.PagedList
@using ResourceCenter.WebCore.Extensions
@model ResourceCenter.WebCore.Modules.Resellers.Models.TranslatedAssetModel

<div class="col-lg-12">
    <div class="ibox">
        <div class="ibox-content product-box custom">
            <div class="row">
                <div class="col-md-5">
                    <div class="product-imitation listItem">
                        @if (string.IsNullOrEmpty(Model.Thumbnail))
                        {
                            <div class="icon">
                                <span></span>@Html.IconFileType(Model.FileName.FileExtension())
                            </div>
                        }
                        else
                        {
                            <span></span><img alt="image" class="img-responsive" src="@Model.Thumbnail">
                        }
                    </div>
                </div>
                <div class="col-md-7 descriptionContent">
                    <h2 class="font-bold m-b-xs">
                        @Model.AssetTitle
                    </h2>
                    <hr>
                    <h4>Product description</h4>
                    <div class="small text-muted">
                        @Model.ShortDescription
                    </div>
                    <hr/>
                    <div class="m-t">
                        <a class="btn btn-xs btn-outline btn-primary" href="@Url.Action("Detail", "Default", ViewContext.RequestContext.ToAssetDetailsRouteValues(Model.Id))">
                            View Details
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>