ResourceCenter.WebUI/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.AutoMapper;
using Core.Web.Mvc.Ajax;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using ResourceCenter.WebCore.Modules.Categories.Models;
using ResourceCenter.WebCore.Modules.Categories.Services;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Areas.Admin.Controllers
{
    public class CategoryController : DistributorAuthorizedController
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> TreeList_Read([DataSourceRequest] DataSourceRequest request)
        {
            var list = await _service.GetList();
            return Json(list.ToTreeDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Create(CreateCategoryModel model)
        {
            try
            {
                var entity = await _service.Create(model);
                return RedirectToAction("Edit", new { id = entity.Id })
                            .WithSuccess("Create successfully");
            }
            catch (Exception ex)
            {
                HandleError(ex);
                return View(model);
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var entity = await _service.Get(id);
            if (entity == null)
            {
                throw NotFoundException();
            }
            return View(entity.MapTo<EditCategoryModel>());
        }

        [HttpPost, ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Edit(int id, EditCategoryModel model)
        {
            try
            {
                await _service.Update(model);
                return RedirectToAction("Edit", new { id = model.Id })
                            .WithSuccess("Update successfully");
            }
            catch (Exception ex)
            {
                HandleError(ex);
                return View(model);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _service.Delete(id);
                return Json(AjaxResult.Success().ToResult());
            }
            catch (Exception ex)
            {
                HandleError(ex);
                return Json(AjaxResult.Error().WithModelState(ModelState).ToResult());
            }
        }
    }
}

ResourceCenter.WebUI/Areas/Admin/Views/Category/Create.cshtml
@using Core.Web.Extensions
@model ResourceCenter.WebCore.Modules.Categories.Models.CreateCategoryModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Category Information</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Create
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index")">
                            <i class="fa fa-arrow-left"></i> Back
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

ResourceCenter.WebUI/Areas/Admin/Views/Category/Edit.cshtml
@using Core.Web.Extensions
@model ResourceCenter.WebCore.Modules.Categories.Models.EditCategoryModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Category Information</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-4">
                            <h2>Edit</h2>
                            @using (Html.FormPost())
                            {
                                @Html.AntiForgeryToken()

                                @Html.ErrorSummary()

                                @Html.EditorForModel("Form")

                                <button class="btn btn-primary ladda-button">
                                    <i class="fa fa-save"></i> Update
                                </button>

                                <a class="btn btn-default" href="@Url.Action("Index")">
                                    <i class="fa fa-arrow-left"></i> Back
                                </a>
                            }
                        </div>

                        <div class="col-sm-8">
                            <h2>Translations</h2>
                            @Html.Action("Index", "CategoryTranslation", new { categoryId = Model.Id })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

ResourceCenter.WebUI/Areas/Admin/Views/Category/Index.cshtml
@using ResourceCenter.WebCore.Modules.Categories.Models

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Category List</h5>
                    <div class="ibox-tools">
                        <div class="buttons">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Create", "Category")">
                                <i class="fa fa-plus"></i> Add new category
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    @(Html.Kendo().TreeList<CategoryPreview>()
                        .Name("treeList")
                        .Columns(columns =>
                        {
                            columns.Add().Field(e => e.Text);
                            columns.Add().Field(e => e.SortOrder);
                            columns.Add()
                                .Template(@"
                                    <a href='/Admin/Category/Edit/#:Id#' class='btn btn-default'><span class='k-icon k-i-edit'></span> Edit</a>
                                    #if (!HasChildren) {#
                                        <button onclick='categoryCtrl.deleteNode(event)' class='btn btn-default'><span class='k-icon k-i-delete'></span> Delete</button>
                                    # } #
                                ")
                                .Sortable(false)
                                .Filterable(false)
                                .Width(190);
                        })
                        .Filterable()
                        .Sortable()
                        .DataSource(dataSource => dataSource
                            .Read(read => read.Action("TreeList_Read", "Category"))
                            .Model(m =>
                            {
                                m.Id(f => f.Id);
                                m.ParentId(f => f.ParentId);
                                m.Expanded(true);
                                m.Field(f => f.Text);
                                m.Field(f => f.SortOrder);
                            })
                        )
                        .Deferred()
                    )
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @ViewHelper.RenderPageScript("admin/category")
}