ResourceCenter.WebUI/Areas/Admin/Controllers/UserLocationController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.AutoMapper;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using ResourceCenter.WebCore.Modules.Location.Models;
using ResourceCenter.WebCore.Modules.Location.Services;
using ResourceCenter.WebUI.Controllers.Base;

namespace ResourceCenter.WebUI.Areas.Admin.Controllers
{
    public class UserLocationController : AuthorizedController
    {
        private readonly IUserLocationService _service;

        public UserLocationController(IUserLocationService service)
        {
            _service = service;
        }

        // GET: Admin/Location
        public ActionResult Index()
        {
            return View();
        }

        #region Grid action
        public JsonResult Grid_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_service.GetList().ToDataSourceResult(request));
        }

        [HttpPost]
        public Task<ActionResult> Grid_Destroy([DataSourceRequest] DataSourceRequest request, UserLocationPreview model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Delete(model));
        }
        #endregion

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Create(UserLocationModel model)
        {
            try
            {
                await _service.Create(model);

                return RedirectToAction("Index").WithSuccess("Create successfully");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            return View((await _service.GetLocation(id)).MapTo<UserLocationModel>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Edit(UserLocationModel model)
        {
            try
            {
                await _service.Update(model);

                return View(model).WithSuccess("Update successfully");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }

            return View(model);
        }
    }
}

ResourceCenter.WebUI/Areas/Admin/Views/UserLocation/Create.cshtml
@using Core.Web.Extensions
@model ResourceCenter.WebCore.Modules.Location.Models.UserLocationModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Location Information</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Create
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "UserLocation")">
                            <i class="fa fa-arrow-left"></i> Back
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @ViewHelper.RenderPageScript("admin/user-location")
    @Html.RenderGoogleMapScript("userLocationCtrl.init")
}

ResourceCenter.WebUI/Areas/Admin/Views/UserLocation/Edit.cshtml
@using Core.Web.Extensions
@model ResourceCenter.WebCore.Modules.Location.Models.UserLocationModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Location Information</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Create
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "UserLocation")">
                            <i class="fa fa-arrow-left"></i> Back
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    @ViewHelper.RenderPageScript("admin/user-location")
    @Html.RenderGoogleMapScript("userLocationCtrl.init")
}

ResourceCenter.WebUI/Areas/Admin/Views/UserLocation/Index.cshtml
@using Core.Web.Kendo
@using ResourceCenter.WebCore.Modules.Location.Models

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Location List</h5>
                    <div class="ibox-tools">
                        <div class="buttons">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Create", "UserLocation", new { area = "Admin" })">
                                <i class="fa fa-plus"></i> Add new location
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    @(Html.Kendo().Grid<UserLocationPreview>()
                        .DefaultSettings()
                        .Columns(columns =>
                        {
                            columns.Bound(p => p.Description).ClientTemplate("<a href='/Admin/UserLocation/Edit/#=Id #'>#=Description #</a>").Width(500);
                            columns.Bound(p => p.ModifiedDate).FormatDateTime();
                            columns.Bound(p => p.ModifiedBy);
                            columns.Command(command => command.Destroy()).Width(110);
                        })
                        .DataSource(dataSource => dataSource
                            .Ajax()
                            .DefaultSettings()
                            .Model(model =>
                            {
                                model.Id(p => p.Id);
                            })
                            .Read(read => read.Action("Grid_Read", "UserLocation"))
                            .Destroy(update => update.Action("Grid_Destroy", "UserLocation"))
                        ).Deferred()
                    )
                </div>
            </div>
        </div>
    </div>
</div>